//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurgerQ.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderproduct
    {
        public int ID { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual orders orders { get; set; }
        public virtual product product { get; set; }
    }
}
